//
//  File.swift
//
//
//  Created by Jakob Mygind on 22/11/2021.
//

import Foundation

extension Foundation.Bundle {
    /// Replacement for the .module autogenerated by Xcode in order to be able to use package in Previews in other packages
    /// - Returns: This bundle
    public static func findBundle<MyClass: AnyObject>(
        thisBundleName: String, classInThisBundle: MyClass.Type
    ) -> Bundle {
        //         The name of your local package, prepended by "LocalPackages_"
        let bundleName = thisBundleName
        let candidates = [
            //             Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,
            //             Bundle should be present here when the package is linked into a framework.
            Bundle(for: MyClass.self).resourceURL,
            //             For command-line tools.
            Bundle.main.bundleURL,
            //             Bundle should be present here when running previews from a different package (this is the path to "…/Debug-iphonesimulator/").
            Bundle(for: MyClass.self).resourceURL?.deletingLastPathComponent()
                .deletingLastPathComponent(),
        ]
        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        fatalError("unable to find bundle named \(bundleName)")
    }
}
