// ----------------------------------------------------------------------
// File generated by NStack Translations Generator v5.0.
//
// Copyright (c) 2018 Nodes ApS
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----------------------------------------------------------------------

import Foundation

#if canImport(NLocalizationManager)
import NLocalizationManager
#endif

#if canImport(LocalizationManager)
import LocalizationManager
#endif
public final class Localizations: LocalizableModel {
    public var searchOrders = SearchOrders()
    public var units = Units()
    public var settings = Settings()
    public var orderDetails = OrderDetails()
    public var login = Login()
    public var dashboard = Dashboard()
    public var orderStatus = OrderStatus()
    public var orderDetailNewOrderSection = OrderDetailNewOrderSection()
    public var printerOutput = PrinterOutput()
    public var defaultSection = DefaultSection()
    public var printer = Printer()
    public var error = Error()
    public var deliveryType = DeliveryType()

    enum CodingKeys: String, CodingKey {
        case searchOrders
        case units
        case settings
        case orderDetails
        case login
        case dashboard
        case orderStatus
        case orderDetailNewOrderSection
        case printerOutput
        case defaultSection = "default"
        case printer
        case error
        case deliveryType
    }

    public override init() { super.init() }

    public required init(from decoder: Decoder) throws {
        super.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        searchOrders = try container.decodeIfPresent(SearchOrders.self, forKey: .searchOrders) ?? searchOrders
        units = try container.decodeIfPresent(Units.self, forKey: .units) ?? units
        settings = try container.decodeIfPresent(Settings.self, forKey: .settings) ?? settings
        orderDetails = try container.decodeIfPresent(OrderDetails.self, forKey: .orderDetails) ?? orderDetails
        login = try container.decodeIfPresent(Login.self, forKey: .login) ?? login
        dashboard = try container.decodeIfPresent(Dashboard.self, forKey: .dashboard) ?? dashboard
        orderStatus = try container.decodeIfPresent(OrderStatus.self, forKey: .orderStatus) ?? orderStatus
        orderDetailNewOrderSection = try container.decodeIfPresent(OrderDetailNewOrderSection.self, forKey: .orderDetailNewOrderSection) ?? orderDetailNewOrderSection
        printerOutput = try container.decodeIfPresent(PrinterOutput.self, forKey: .printerOutput) ?? printerOutput
        defaultSection = try container.decodeIfPresent(DefaultSection.self, forKey: .defaultSection) ?? defaultSection
        printer = try container.decodeIfPresent(Printer.self, forKey: .printer) ?? printer
        error = try container.decodeIfPresent(Error.self, forKey: .error) ?? error
        deliveryType = try container.decodeIfPresent(DeliveryType.self, forKey: .deliveryType) ?? deliveryType
    }

    public override subscript(key: String) -> LocalizableSection? {
        switch key {
        case CodingKeys.searchOrders.stringValue: return searchOrders
        case CodingKeys.units.stringValue: return units
        case CodingKeys.settings.stringValue: return settings
        case CodingKeys.orderDetails.stringValue: return orderDetails
        case CodingKeys.login.stringValue: return login
        case CodingKeys.dashboard.stringValue: return dashboard
        case CodingKeys.orderStatus.stringValue: return orderStatus
        case CodingKeys.orderDetailNewOrderSection.stringValue: return orderDetailNewOrderSection
        case CodingKeys.printerOutput.stringValue: return printerOutput
        case CodingKeys.defaultSection.stringValue: return defaultSection
        case CodingKeys.printer.stringValue: return printer
        case CodingKeys.error.stringValue: return error
        case CodingKeys.deliveryType.stringValue: return deliveryType
        default: return nil
        }
    }

    public final class SearchOrders: LocalizableSection {
        public var statusRejected = ""
        public var statusNew = ""
        public var statusReady = ""
        public var customerNameHeader = ""
        public var title = ""
        public var orderNumberHeader = ""
        public var orderStatusHeader = ""
        public var orderDateHeader = ""
        public var statusAccepted = ""
        public var searchfieldPlaceholder = ""
        public var emptyMessage = ""
        public var statusCompleted = ""
        public var statusShipped = ""

        enum CodingKeys: String, CodingKey {
            case statusRejected
            case statusNew
            case statusReady
            case customerNameHeader
            case title
            case orderNumberHeader
            case orderStatusHeader
            case orderDateHeader
            case statusAccepted
            case searchfieldPlaceholder
            case emptyMessage
            case statusCompleted
            case statusShipped
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            statusRejected = try container.decodeIfPresent(String.self, forKey: .statusRejected) ?? "__statusRejected"
            statusNew = try container.decodeIfPresent(String.self, forKey: .statusNew) ?? "__statusNew"
            statusReady = try container.decodeIfPresent(String.self, forKey: .statusReady) ?? "__statusReady"
            customerNameHeader = try container.decodeIfPresent(String.self, forKey: .customerNameHeader) ?? "__customerNameHeader"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            orderNumberHeader = try container.decodeIfPresent(String.self, forKey: .orderNumberHeader) ?? "__orderNumberHeader"
            orderStatusHeader = try container.decodeIfPresent(String.self, forKey: .orderStatusHeader) ?? "__orderStatusHeader"
            orderDateHeader = try container.decodeIfPresent(String.self, forKey: .orderDateHeader) ?? "__orderDateHeader"
            statusAccepted = try container.decodeIfPresent(String.self, forKey: .statusAccepted) ?? "__statusAccepted"
            searchfieldPlaceholder = try container.decodeIfPresent(String.self, forKey: .searchfieldPlaceholder) ?? "__searchfieldPlaceholder"
            emptyMessage = try container.decodeIfPresent(String.self, forKey: .emptyMessage) ?? "__emptyMessage"
            statusCompleted = try container.decodeIfPresent(String.self, forKey: .statusCompleted) ?? "__statusCompleted"
            statusShipped = try container.decodeIfPresent(String.self, forKey: .statusShipped) ?? "__statusShipped"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.statusRejected.stringValue: return statusRejected
            case CodingKeys.statusNew.stringValue: return statusNew
            case CodingKeys.statusReady.stringValue: return statusReady
            case CodingKeys.customerNameHeader.stringValue: return customerNameHeader
            case CodingKeys.title.stringValue: return title
            case CodingKeys.orderNumberHeader.stringValue: return orderNumberHeader
            case CodingKeys.orderStatusHeader.stringValue: return orderStatusHeader
            case CodingKeys.orderDateHeader.stringValue: return orderDateHeader
            case CodingKeys.statusAccepted.stringValue: return statusAccepted
            case CodingKeys.searchfieldPlaceholder.stringValue: return searchfieldPlaceholder
            case CodingKeys.emptyMessage.stringValue: return emptyMessage
            case CodingKeys.statusCompleted.stringValue: return statusCompleted
            case CodingKeys.statusShipped.stringValue: return statusShipped
            default: return nil
            }
        }
    }

    public final class Units: LocalizableSection {
        public var d70 = ""
        public var ltr = ""
        public var clt = ""
        public var grm = ""
        public var cmt = ""
        public var h87 = ""
        public var e14 = ""
        public var dlt = ""
        public var kgm = ""
        public var mlt = ""

        enum CodingKeys: String, CodingKey {
            case d70
            case ltr
            case clt
            case grm
            case cmt
            case h87
            case e14
            case dlt
            case kgm
            case mlt
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            d70 = try container.decodeIfPresent(String.self, forKey: .d70) ?? "__d70"
            ltr = try container.decodeIfPresent(String.self, forKey: .ltr) ?? "__ltr"
            clt = try container.decodeIfPresent(String.self, forKey: .clt) ?? "__clt"
            grm = try container.decodeIfPresent(String.self, forKey: .grm) ?? "__grm"
            cmt = try container.decodeIfPresent(String.self, forKey: .cmt) ?? "__cmt"
            h87 = try container.decodeIfPresent(String.self, forKey: .h87) ?? "__h87"
            e14 = try container.decodeIfPresent(String.self, forKey: .e14) ?? "__e14"
            dlt = try container.decodeIfPresent(String.self, forKey: .dlt) ?? "__dlt"
            kgm = try container.decodeIfPresent(String.self, forKey: .kgm) ?? "__kgm"
            mlt = try container.decodeIfPresent(String.self, forKey: .mlt) ?? "__mlt"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.d70.stringValue: return d70
            case CodingKeys.ltr.stringValue: return ltr
            case CodingKeys.clt.stringValue: return clt
            case CodingKeys.grm.stringValue: return grm
            case CodingKeys.cmt.stringValue: return cmt
            case CodingKeys.h87.stringValue: return h87
            case CodingKeys.e14.stringValue: return e14
            case CodingKeys.dlt.stringValue: return dlt
            case CodingKeys.kgm.stringValue: return kgm
            case CodingKeys.mlt.stringValue: return mlt
            default: return nil
            }
        }
    }

    public final class Settings: LocalizableSection {
        public var selectPrinterButton = ""
        public var logOutButton = ""
        public var title = ""
        public var closeButton = ""
        public var logOutAlertCancel = ""
        public var logoutAlertTitle = ""
        public var logOutAlertConfirm = ""
        public var logOutAlertMessage = ""
        public var printerHeader = ""
        public var usernameHeader = ""
        public var appVersionHeader = ""

        enum CodingKeys: String, CodingKey {
            case selectPrinterButton
            case logOutButton
            case title
            case closeButton
            case logOutAlertCancel
            case logoutAlertTitle
            case logOutAlertConfirm
            case logOutAlertMessage
            case printerHeader
            case usernameHeader
            case appVersionHeader
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            selectPrinterButton = try container.decodeIfPresent(String.self, forKey: .selectPrinterButton) ?? "__selectPrinterButton"
            logOutButton = try container.decodeIfPresent(String.self, forKey: .logOutButton) ?? "__logOutButton"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            closeButton = try container.decodeIfPresent(String.self, forKey: .closeButton) ?? "__closeButton"
            logOutAlertCancel = try container.decodeIfPresent(String.self, forKey: .logOutAlertCancel) ?? "__logOutAlertCancel"
            logoutAlertTitle = try container.decodeIfPresent(String.self, forKey: .logoutAlertTitle) ?? "__logoutAlertTitle"
            logOutAlertConfirm = try container.decodeIfPresent(String.self, forKey: .logOutAlertConfirm) ?? "__logOutAlertConfirm"
            logOutAlertMessage = try container.decodeIfPresent(String.self, forKey: .logOutAlertMessage) ?? "__logOutAlertMessage"
            printerHeader = try container.decodeIfPresent(String.self, forKey: .printerHeader) ?? "__printerHeader"
            usernameHeader = try container.decodeIfPresent(String.self, forKey: .usernameHeader) ?? "__usernameHeader"
            appVersionHeader = try container.decodeIfPresent(String.self, forKey: .appVersionHeader) ?? "__appVersionHeader"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.selectPrinterButton.stringValue: return selectPrinterButton
            case CodingKeys.logOutButton.stringValue: return logOutButton
            case CodingKeys.title.stringValue: return title
            case CodingKeys.closeButton.stringValue: return closeButton
            case CodingKeys.logOutAlertCancel.stringValue: return logOutAlertCancel
            case CodingKeys.logoutAlertTitle.stringValue: return logoutAlertTitle
            case CodingKeys.logOutAlertConfirm.stringValue: return logOutAlertConfirm
            case CodingKeys.logOutAlertMessage.stringValue: return logOutAlertMessage
            case CodingKeys.printerHeader.stringValue: return printerHeader
            case CodingKeys.usernameHeader.stringValue: return usernameHeader
            case CodingKeys.appVersionHeader.stringValue: return appVersionHeader
            default: return nil
            }
        }
    }

    public final class OrderDetails: LocalizableSection {
        public var infoEmail = ""
        public var sectionHeaderWarmProducts = ""
        public var completedBanner = ""
        public var infoPaymentType = ""
        public var printButton = ""
        public var outForDeliveryButton = ""
        public var pickedUpButton = ""
        public var infoAddress = ""
        public var infoTakeoutPhone = ""
        public var today = ""
        public var sectionHeaderColdProducts = ""
        public var errorStatusUpdateFailed = ""
        public var rejectOrderAlertTitle = ""
        public var infoTakeOutShopID = ""
        public var sectionHeaderTakeout = ""
        public var sectionHeaderCustomerInfo = ""
        public var infoOrderTime = ""
        public var pickupTimeHeader = ""
        public var infoDeliveryTime = ""
        public var errorCouldNotFetchProducts = ""
        public var sectionHeaderOtherProducts = ""
        public var sectionHeaderOrderStatus = ""
        public var rejectOrderAlertCancel = ""
        public var aPiece = ""
        public var includeCutlery = ""
        public var sectionSubheaderColdProducts = ""
        public var underPreparationButton = ""
        public var deliveryTypeHeader = ""
        public var rejectOrderAlertMessage = ""
        public var rejectOrderAlertConfirm = ""
        public var infoCustomerName = ""
        public var rejectButton = ""
        public var customerNoteHeader = ""
        public var infoMobilePhone = ""
        public var readyButton = ""

        enum CodingKeys: String, CodingKey {
            case infoEmail
            case sectionHeaderWarmProducts
            case completedBanner
            case infoPaymentType
            case printButton
            case outForDeliveryButton
            case pickedUpButton
            case infoAddress
            case infoTakeoutPhone
            case today
            case sectionHeaderColdProducts
            case errorStatusUpdateFailed
            case rejectOrderAlertTitle
            case infoTakeOutShopID
            case sectionHeaderTakeout
            case sectionHeaderCustomerInfo
            case infoOrderTime
            case pickupTimeHeader
            case infoDeliveryTime
            case errorCouldNotFetchProducts
            case sectionHeaderOtherProducts
            case sectionHeaderOrderStatus
            case rejectOrderAlertCancel
            case aPiece
            case includeCutlery
            case sectionSubheaderColdProducts
            case underPreparationButton
            case deliveryTypeHeader
            case rejectOrderAlertMessage
            case rejectOrderAlertConfirm
            case infoCustomerName
            case rejectButton
            case customerNoteHeader
            case infoMobilePhone
            case readyButton
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            infoEmail = try container.decodeIfPresent(String.self, forKey: .infoEmail) ?? "__infoEmail"
            sectionHeaderWarmProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderWarmProducts) ?? "__sectionHeaderWarmProducts"
            completedBanner = try container.decodeIfPresent(String.self, forKey: .completedBanner) ?? "__completedBanner"
            infoPaymentType = try container.decodeIfPresent(String.self, forKey: .infoPaymentType) ?? "__infoPaymentType"
            printButton = try container.decodeIfPresent(String.self, forKey: .printButton) ?? "__printButton"
            outForDeliveryButton = try container.decodeIfPresent(String.self, forKey: .outForDeliveryButton) ?? "__outForDeliveryButton"
            pickedUpButton = try container.decodeIfPresent(String.self, forKey: .pickedUpButton) ?? "__pickedUpButton"
            infoAddress = try container.decodeIfPresent(String.self, forKey: .infoAddress) ?? "__infoAddress"
            infoTakeoutPhone = try container.decodeIfPresent(String.self, forKey: .infoTakeoutPhone) ?? "__infoTakeoutPhone"
            today = try container.decodeIfPresent(String.self, forKey: .today) ?? "__today"
            sectionHeaderColdProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderColdProducts) ?? "__sectionHeaderColdProducts"
            errorStatusUpdateFailed = try container.decodeIfPresent(String.self, forKey: .errorStatusUpdateFailed) ?? "__errorStatusUpdateFailed"
            rejectOrderAlertTitle = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertTitle) ?? "__rejectOrderAlertTitle"
            infoTakeOutShopID = try container.decodeIfPresent(String.self, forKey: .infoTakeOutShopID) ?? "__infoTakeOutShopID"
            sectionHeaderTakeout = try container.decodeIfPresent(String.self, forKey: .sectionHeaderTakeout) ?? "__sectionHeaderTakeout"
            sectionHeaderCustomerInfo = try container.decodeIfPresent(String.self, forKey: .sectionHeaderCustomerInfo) ?? "__sectionHeaderCustomerInfo"
            infoOrderTime = try container.decodeIfPresent(String.self, forKey: .infoOrderTime) ?? "__infoOrderTime"
            pickupTimeHeader = try container.decodeIfPresent(String.self, forKey: .pickupTimeHeader) ?? "__pickupTimeHeader"
            infoDeliveryTime = try container.decodeIfPresent(String.self, forKey: .infoDeliveryTime) ?? "__infoDeliveryTime"
            errorCouldNotFetchProducts = try container.decodeIfPresent(String.self, forKey: .errorCouldNotFetchProducts) ?? "__errorCouldNotFetchProducts"
            sectionHeaderOtherProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderOtherProducts) ?? "__sectionHeaderOtherProducts"
            sectionHeaderOrderStatus = try container.decodeIfPresent(String.self, forKey: .sectionHeaderOrderStatus) ?? "__sectionHeaderOrderStatus"
            rejectOrderAlertCancel = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertCancel) ?? "__rejectOrderAlertCancel"
            aPiece = try container.decodeIfPresent(String.self, forKey: .aPiece) ?? "__aPiece"
            includeCutlery = try container.decodeIfPresent(String.self, forKey: .includeCutlery) ?? "__includeCutlery"
            sectionSubheaderColdProducts = try container.decodeIfPresent(String.self, forKey: .sectionSubheaderColdProducts) ?? "__sectionSubheaderColdProducts"
            underPreparationButton = try container.decodeIfPresent(String.self, forKey: .underPreparationButton) ?? "__underPreparationButton"
            deliveryTypeHeader = try container.decodeIfPresent(String.self, forKey: .deliveryTypeHeader) ?? "__deliveryTypeHeader"
            rejectOrderAlertMessage = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertMessage) ?? "__rejectOrderAlertMessage"
            rejectOrderAlertConfirm = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertConfirm) ?? "__rejectOrderAlertConfirm"
            infoCustomerName = try container.decodeIfPresent(String.self, forKey: .infoCustomerName) ?? "__infoCustomerName"
            rejectButton = try container.decodeIfPresent(String.self, forKey: .rejectButton) ?? "__rejectButton"
            customerNoteHeader = try container.decodeIfPresent(String.self, forKey: .customerNoteHeader) ?? "__customerNoteHeader"
            infoMobilePhone = try container.decodeIfPresent(String.self, forKey: .infoMobilePhone) ?? "__infoMobilePhone"
            readyButton = try container.decodeIfPresent(String.self, forKey: .readyButton) ?? "__readyButton"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.infoEmail.stringValue: return infoEmail
            case CodingKeys.sectionHeaderWarmProducts.stringValue: return sectionHeaderWarmProducts
            case CodingKeys.completedBanner.stringValue: return completedBanner
            case CodingKeys.infoPaymentType.stringValue: return infoPaymentType
            case CodingKeys.printButton.stringValue: return printButton
            case CodingKeys.outForDeliveryButton.stringValue: return outForDeliveryButton
            case CodingKeys.pickedUpButton.stringValue: return pickedUpButton
            case CodingKeys.infoAddress.stringValue: return infoAddress
            case CodingKeys.infoTakeoutPhone.stringValue: return infoTakeoutPhone
            case CodingKeys.today.stringValue: return today
            case CodingKeys.sectionHeaderColdProducts.stringValue: return sectionHeaderColdProducts
            case CodingKeys.errorStatusUpdateFailed.stringValue: return errorStatusUpdateFailed
            case CodingKeys.rejectOrderAlertTitle.stringValue: return rejectOrderAlertTitle
            case CodingKeys.infoTakeOutShopID.stringValue: return infoTakeOutShopID
            case CodingKeys.sectionHeaderTakeout.stringValue: return sectionHeaderTakeout
            case CodingKeys.sectionHeaderCustomerInfo.stringValue: return sectionHeaderCustomerInfo
            case CodingKeys.infoOrderTime.stringValue: return infoOrderTime
            case CodingKeys.pickupTimeHeader.stringValue: return pickupTimeHeader
            case CodingKeys.infoDeliveryTime.stringValue: return infoDeliveryTime
            case CodingKeys.errorCouldNotFetchProducts.stringValue: return errorCouldNotFetchProducts
            case CodingKeys.sectionHeaderOtherProducts.stringValue: return sectionHeaderOtherProducts
            case CodingKeys.sectionHeaderOrderStatus.stringValue: return sectionHeaderOrderStatus
            case CodingKeys.rejectOrderAlertCancel.stringValue: return rejectOrderAlertCancel
            case CodingKeys.aPiece.stringValue: return aPiece
            case CodingKeys.includeCutlery.stringValue: return includeCutlery
            case CodingKeys.sectionSubheaderColdProducts.stringValue: return sectionSubheaderColdProducts
            case CodingKeys.underPreparationButton.stringValue: return underPreparationButton
            case CodingKeys.deliveryTypeHeader.stringValue: return deliveryTypeHeader
            case CodingKeys.rejectOrderAlertMessage.stringValue: return rejectOrderAlertMessage
            case CodingKeys.rejectOrderAlertConfirm.stringValue: return rejectOrderAlertConfirm
            case CodingKeys.infoCustomerName.stringValue: return infoCustomerName
            case CodingKeys.rejectButton.stringValue: return rejectButton
            case CodingKeys.customerNoteHeader.stringValue: return customerNoteHeader
            case CodingKeys.infoMobilePhone.stringValue: return infoMobilePhone
            case CodingKeys.readyButton.stringValue: return readyButton
            default: return nil
            }
        }
    }

    public final class Login: LocalizableSection {
        public var appName = ""
        public var loginButton = ""
        public var emailPlaceholder = ""
        public var errorInvalidCredentials = ""
        public var title = ""
        public var appVersionPrefix = ""
        public var emailHeader = ""
        public var passwordPlaceholder = ""
        public var passwordHeader = ""
        public var resetPasswordMessage = ""

        enum CodingKeys: String, CodingKey {
            case appName
            case loginButton
            case emailPlaceholder
            case errorInvalidCredentials
            case title
            case appVersionPrefix
            case emailHeader
            case passwordPlaceholder
            case passwordHeader
            case resetPasswordMessage
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            appName = try container.decodeIfPresent(String.self, forKey: .appName) ?? "__appName"
            loginButton = try container.decodeIfPresent(String.self, forKey: .loginButton) ?? "__loginButton"
            emailPlaceholder = try container.decodeIfPresent(String.self, forKey: .emailPlaceholder) ?? "__emailPlaceholder"
            errorInvalidCredentials = try container.decodeIfPresent(String.self, forKey: .errorInvalidCredentials) ?? "__errorInvalidCredentials"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            appVersionPrefix = try container.decodeIfPresent(String.self, forKey: .appVersionPrefix) ?? "__appVersionPrefix"
            emailHeader = try container.decodeIfPresent(String.self, forKey: .emailHeader) ?? "__emailHeader"
            passwordPlaceholder = try container.decodeIfPresent(String.self, forKey: .passwordPlaceholder) ?? "__passwordPlaceholder"
            passwordHeader = try container.decodeIfPresent(String.self, forKey: .passwordHeader) ?? "__passwordHeader"
            resetPasswordMessage = try container.decodeIfPresent(String.self, forKey: .resetPasswordMessage) ?? "__resetPasswordMessage"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.appName.stringValue: return appName
            case CodingKeys.loginButton.stringValue: return loginButton
            case CodingKeys.emailPlaceholder.stringValue: return emailPlaceholder
            case CodingKeys.errorInvalidCredentials.stringValue: return errorInvalidCredentials
            case CodingKeys.title.stringValue: return title
            case CodingKeys.appVersionPrefix.stringValue: return appVersionPrefix
            case CodingKeys.emailHeader.stringValue: return emailHeader
            case CodingKeys.passwordPlaceholder.stringValue: return passwordPlaceholder
            case CodingKeys.passwordHeader.stringValue: return passwordHeader
            case CodingKeys.resetPasswordMessage.stringValue: return resetPasswordMessage
            default: return nil
            }
        }
    }

    public final class Dashboard: LocalizableSection {
        public var sectionTomorrow = ""
        public var columnDoneTodayEmpty = ""
        public var sectionLater = ""
        public var allOrdersButton = ""
        public var columnReadyEmpty = ""
        public var columnIncomingEmpty = ""
        public var columnAcceptedEmpty = ""
        public var columnDoneToday = ""
        public var sectionToday = ""
        public var columnOutForDeliveryEmpty = ""
        public var columnIncoming = ""
        public var itemsSingular = ""
        public var columnAccepted = ""
        public var columnOutForDelivery = ""
        public var itemsPlural = ""
        public var columnReady = ""

        enum CodingKeys: String, CodingKey {
            case sectionTomorrow
            case columnDoneTodayEmpty
            case sectionLater
            case allOrdersButton
            case columnReadyEmpty
            case columnIncomingEmpty
            case columnAcceptedEmpty
            case columnDoneToday
            case sectionToday
            case columnOutForDeliveryEmpty
            case columnIncoming
            case itemsSingular
            case columnAccepted
            case columnOutForDelivery
            case itemsPlural
            case columnReady
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            sectionTomorrow = try container.decodeIfPresent(String.self, forKey: .sectionTomorrow) ?? "__sectionTomorrow"
            columnDoneTodayEmpty = try container.decodeIfPresent(String.self, forKey: .columnDoneTodayEmpty) ?? "__columnDoneTodayEmpty"
            sectionLater = try container.decodeIfPresent(String.self, forKey: .sectionLater) ?? "__sectionLater"
            allOrdersButton = try container.decodeIfPresent(String.self, forKey: .allOrdersButton) ?? "__allOrdersButton"
            columnReadyEmpty = try container.decodeIfPresent(String.self, forKey: .columnReadyEmpty) ?? "__columnReadyEmpty"
            columnIncomingEmpty = try container.decodeIfPresent(String.self, forKey: .columnIncomingEmpty) ?? "__columnIncomingEmpty"
            columnAcceptedEmpty = try container.decodeIfPresent(String.self, forKey: .columnAcceptedEmpty) ?? "__columnAcceptedEmpty"
            columnDoneToday = try container.decodeIfPresent(String.self, forKey: .columnDoneToday) ?? "__columnDoneToday"
            sectionToday = try container.decodeIfPresent(String.self, forKey: .sectionToday) ?? "__sectionToday"
            columnOutForDeliveryEmpty = try container.decodeIfPresent(String.self, forKey: .columnOutForDeliveryEmpty) ?? "__columnOutForDeliveryEmpty"
            columnIncoming = try container.decodeIfPresent(String.self, forKey: .columnIncoming) ?? "__columnIncoming"
            itemsSingular = try container.decodeIfPresent(String.self, forKey: .itemsSingular) ?? "__itemsSingular"
            columnAccepted = try container.decodeIfPresent(String.self, forKey: .columnAccepted) ?? "__columnAccepted"
            columnOutForDelivery = try container.decodeIfPresent(String.self, forKey: .columnOutForDelivery) ?? "__columnOutForDelivery"
            itemsPlural = try container.decodeIfPresent(String.self, forKey: .itemsPlural) ?? "__itemsPlural"
            columnReady = try container.decodeIfPresent(String.self, forKey: .columnReady) ?? "__columnReady"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.sectionTomorrow.stringValue: return sectionTomorrow
            case CodingKeys.columnDoneTodayEmpty.stringValue: return columnDoneTodayEmpty
            case CodingKeys.sectionLater.stringValue: return sectionLater
            case CodingKeys.allOrdersButton.stringValue: return allOrdersButton
            case CodingKeys.columnReadyEmpty.stringValue: return columnReadyEmpty
            case CodingKeys.columnIncomingEmpty.stringValue: return columnIncomingEmpty
            case CodingKeys.columnAcceptedEmpty.stringValue: return columnAcceptedEmpty
            case CodingKeys.columnDoneToday.stringValue: return columnDoneToday
            case CodingKeys.sectionToday.stringValue: return sectionToday
            case CodingKeys.columnOutForDeliveryEmpty.stringValue: return columnOutForDeliveryEmpty
            case CodingKeys.columnIncoming.stringValue: return columnIncoming
            case CodingKeys.itemsSingular.stringValue: return itemsSingular
            case CodingKeys.columnAccepted.stringValue: return columnAccepted
            case CodingKeys.columnOutForDelivery.stringValue: return columnOutForDelivery
            case CodingKeys.itemsPlural.stringValue: return itemsPlural
            case CodingKeys.columnReady.stringValue: return columnReady
            default: return nil
            }
        }
    }

    public final class OrderStatus: LocalizableSection {
        public var accepted = ""

        enum CodingKeys: String, CodingKey {
            case accepted
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            accepted = try container.decodeIfPresent(String.self, forKey: .accepted) ?? "__accepted"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.accepted.stringValue: return accepted
            default: return nil
            }
        }
    }

    public final class OrderDetailNewOrderSection: LocalizableSection {
        public var acceptButton = ""
        public var phoneNumberHeader = ""
        public var header = ""
        public var pickupTimeHeader = ""
        public var subheader = ""
        public var customerNameHeader = ""
        public var deliveryTimeHeader = ""
        public var pickedUpInStoreAt = ""
        public var rejectButton = ""

        enum CodingKeys: String, CodingKey {
            case acceptButton
            case phoneNumberHeader
            case header
            case pickupTimeHeader
            case subheader
            case customerNameHeader
            case deliveryTimeHeader
            case pickedUpInStoreAt
            case rejectButton
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            acceptButton = try container.decodeIfPresent(String.self, forKey: .acceptButton) ?? "__acceptButton"
            phoneNumberHeader = try container.decodeIfPresent(String.self, forKey: .phoneNumberHeader) ?? "__phoneNumberHeader"
            header = try container.decodeIfPresent(String.self, forKey: .header) ?? "__header"
            pickupTimeHeader = try container.decodeIfPresent(String.self, forKey: .pickupTimeHeader) ?? "__pickupTimeHeader"
            subheader = try container.decodeIfPresent(String.self, forKey: .subheader) ?? "__subheader"
            customerNameHeader = try container.decodeIfPresent(String.self, forKey: .customerNameHeader) ?? "__customerNameHeader"
            deliveryTimeHeader = try container.decodeIfPresent(String.self, forKey: .deliveryTimeHeader) ?? "__deliveryTimeHeader"
            pickedUpInStoreAt = try container.decodeIfPresent(String.self, forKey: .pickedUpInStoreAt) ?? "__pickedUpInStoreAt"
            rejectButton = try container.decodeIfPresent(String.self, forKey: .rejectButton) ?? "__rejectButton"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.acceptButton.stringValue: return acceptButton
            case CodingKeys.phoneNumberHeader.stringValue: return phoneNumberHeader
            case CodingKeys.header.stringValue: return header
            case CodingKeys.pickupTimeHeader.stringValue: return pickupTimeHeader
            case CodingKeys.subheader.stringValue: return subheader
            case CodingKeys.customerNameHeader.stringValue: return customerNameHeader
            case CodingKeys.deliveryTimeHeader.stringValue: return deliveryTimeHeader
            case CodingKeys.pickedUpInStoreAt.stringValue: return pickedUpInStoreAt
            case CodingKeys.rejectButton.stringValue: return rejectButton
            default: return nil
            }
        }
    }

    public final class PrinterOutput: LocalizableSection {
        public var orderNumber = ""
        public var errorDeviceConnectionFailed = ""
        public var includeCutlery = ""
        public var warmHeader = ""
        public var otherHeader = ""
        public var errorNoDeviceFound = ""
        public var coldHeader = ""
        public var noteHeader = ""

        enum CodingKeys: String, CodingKey {
            case orderNumber
            case errorDeviceConnectionFailed
            case includeCutlery
            case warmHeader
            case otherHeader
            case errorNoDeviceFound
            case coldHeader
            case noteHeader
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            orderNumber = try container.decodeIfPresent(String.self, forKey: .orderNumber) ?? "__orderNumber"
            errorDeviceConnectionFailed = try container.decodeIfPresent(String.self, forKey: .errorDeviceConnectionFailed) ?? "__errorDeviceConnectionFailed"
            includeCutlery = try container.decodeIfPresent(String.self, forKey: .includeCutlery) ?? "__includeCutlery"
            warmHeader = try container.decodeIfPresent(String.self, forKey: .warmHeader) ?? "__warmHeader"
            otherHeader = try container.decodeIfPresent(String.self, forKey: .otherHeader) ?? "__otherHeader"
            errorNoDeviceFound = try container.decodeIfPresent(String.self, forKey: .errorNoDeviceFound) ?? "__errorNoDeviceFound"
            coldHeader = try container.decodeIfPresent(String.self, forKey: .coldHeader) ?? "__coldHeader"
            noteHeader = try container.decodeIfPresent(String.self, forKey: .noteHeader) ?? "__noteHeader"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.orderNumber.stringValue: return orderNumber
            case CodingKeys.errorDeviceConnectionFailed.stringValue: return errorDeviceConnectionFailed
            case CodingKeys.includeCutlery.stringValue: return includeCutlery
            case CodingKeys.warmHeader.stringValue: return warmHeader
            case CodingKeys.otherHeader.stringValue: return otherHeader
            case CodingKeys.errorNoDeviceFound.stringValue: return errorNoDeviceFound
            case CodingKeys.coldHeader.stringValue: return coldHeader
            case CodingKeys.noteHeader.stringValue: return noteHeader
            default: return nil
            }
        }
    }

    public final class DefaultSection: LocalizableSection {
        public var previous = ""
        public var retry = ""
        public var no = ""
        public var back = ""
        public var next = ""
        public var skip = ""
        public var settings = ""
        public var later = ""
        public var yes = ""
        public var ok = ""
        public var edit = ""
        public var cancel = ""
        public var save = ""

        enum CodingKeys: String, CodingKey {
            case previous
            case retry
            case no
            case back
            case next
            case skip
            case settings
            case later
            case yes
            case ok
            case edit
            case cancel
            case save
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            previous = try container.decodeIfPresent(String.self, forKey: .previous) ?? "__previous"
            retry = try container.decodeIfPresent(String.self, forKey: .retry) ?? "__retry"
            no = try container.decodeIfPresent(String.self, forKey: .no) ?? "__no"
            back = try container.decodeIfPresent(String.self, forKey: .back) ?? "__back"
            next = try container.decodeIfPresent(String.self, forKey: .next) ?? "__next"
            skip = try container.decodeIfPresent(String.self, forKey: .skip) ?? "__skip"
            settings = try container.decodeIfPresent(String.self, forKey: .settings) ?? "__settings"
            later = try container.decodeIfPresent(String.self, forKey: .later) ?? "__later"
            yes = try container.decodeIfPresent(String.self, forKey: .yes) ?? "__yes"
            ok = try container.decodeIfPresent(String.self, forKey: .ok) ?? "__ok"
            edit = try container.decodeIfPresent(String.self, forKey: .edit) ?? "__edit"
            cancel = try container.decodeIfPresent(String.self, forKey: .cancel) ?? "__cancel"
            save = try container.decodeIfPresent(String.self, forKey: .save) ?? "__save"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.previous.stringValue: return previous
            case CodingKeys.retry.stringValue: return retry
            case CodingKeys.no.stringValue: return no
            case CodingKeys.back.stringValue: return back
            case CodingKeys.next.stringValue: return next
            case CodingKeys.skip.stringValue: return skip
            case CodingKeys.settings.stringValue: return settings
            case CodingKeys.later.stringValue: return later
            case CodingKeys.yes.stringValue: return yes
            case CodingKeys.ok.stringValue: return ok
            case CodingKeys.edit.stringValue: return edit
            case CodingKeys.cancel.stringValue: return cancel
            case CodingKeys.save.stringValue: return save
            default: return nil
            }
        }
    }

    public final class Printer: LocalizableSection {
        public var deleteButton = ""
        public var connectButton = ""
        public var sectionHeaderActivePrinter = ""
        public var title = ""
        public var connectedSuccessMessage = ""
        public var errorSomethingHappened = ""
        public var bluetoothHintFooter = ""
        public var sectionHeaderNewPrinters = ""

        enum CodingKeys: String, CodingKey {
            case deleteButton
            case connectButton
            case sectionHeaderActivePrinter
            case title
            case connectedSuccessMessage
            case errorSomethingHappened
            case bluetoothHintFooter
            case sectionHeaderNewPrinters
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            deleteButton = try container.decodeIfPresent(String.self, forKey: .deleteButton) ?? "__deleteButton"
            connectButton = try container.decodeIfPresent(String.self, forKey: .connectButton) ?? "__connectButton"
            sectionHeaderActivePrinter = try container.decodeIfPresent(String.self, forKey: .sectionHeaderActivePrinter) ?? "__sectionHeaderActivePrinter"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            connectedSuccessMessage = try container.decodeIfPresent(String.self, forKey: .connectedSuccessMessage) ?? "__connectedSuccessMessage"
            errorSomethingHappened = try container.decodeIfPresent(String.self, forKey: .errorSomethingHappened) ?? "__errorSomethingHappened"
            bluetoothHintFooter = try container.decodeIfPresent(String.self, forKey: .bluetoothHintFooter) ?? "__bluetoothHintFooter"
            sectionHeaderNewPrinters = try container.decodeIfPresent(String.self, forKey: .sectionHeaderNewPrinters) ?? "__sectionHeaderNewPrinters"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.deleteButton.stringValue: return deleteButton
            case CodingKeys.connectButton.stringValue: return connectButton
            case CodingKeys.sectionHeaderActivePrinter.stringValue: return sectionHeaderActivePrinter
            case CodingKeys.title.stringValue: return title
            case CodingKeys.connectedSuccessMessage.stringValue: return connectedSuccessMessage
            case CodingKeys.errorSomethingHappened.stringValue: return errorSomethingHappened
            case CodingKeys.bluetoothHintFooter.stringValue: return bluetoothHintFooter
            case CodingKeys.sectionHeaderNewPrinters.stringValue: return sectionHeaderNewPrinters
            default: return nil
            }
        }
    }

    public final class Error: LocalizableSection {
        public var errorTitle = ""
        public var serverError = ""
        public var unknownError = ""
        public var connectionError = ""
        public var authenticationError = ""

        enum CodingKeys: String, CodingKey {
            case errorTitle
            case serverError
            case unknownError
            case connectionError
            case authenticationError
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            errorTitle = try container.decodeIfPresent(String.self, forKey: .errorTitle) ?? "__errorTitle"
            serverError = try container.decodeIfPresent(String.self, forKey: .serverError) ?? "__serverError"
            unknownError = try container.decodeIfPresent(String.self, forKey: .unknownError) ?? "__unknownError"
            connectionError = try container.decodeIfPresent(String.self, forKey: .connectionError) ?? "__connectionError"
            authenticationError = try container.decodeIfPresent(String.self, forKey: .authenticationError) ?? "__authenticationError"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.errorTitle.stringValue: return errorTitle
            case CodingKeys.serverError.stringValue: return serverError
            case CodingKeys.unknownError.stringValue: return unknownError
            case CodingKeys.connectionError.stringValue: return connectionError
            case CodingKeys.authenticationError.stringValue: return authenticationError
            default: return nil
            }
        }
    }

    public final class DeliveryType: LocalizableSection {
        public var collect = ""
        public var delivery = ""

        enum CodingKeys: String, CodingKey {
            case collect
            case delivery
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            collect = try container.decodeIfPresent(String.self, forKey: .collect) ?? "__collect"
            delivery = try container.decodeIfPresent(String.self, forKey: .delivery) ?? "__delivery"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.collect.stringValue: return collect
            case CodingKeys.delivery.stringValue: return delivery
            default: return nil
            }
        }
    }
}

