// ----------------------------------------------------------------------
// File generated by NStack Translations Generator v5.0.
//
// Copyright (c) 2018 Nodes ApS
//
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----------------------------------------------------------------------

import Foundation

#if canImport(NLocalizationManager)
import NLocalizationManager
#endif

#if canImport(LocalizationManager)
import LocalizationManager
#endif
public final class Localizations: LocalizableModel {
    public var orderDetailNewOrderSection = OrderDetailNewOrderSection()
    public var error = Error()
    public var printerOutput = PrinterOutput()
    public var searchOrders = SearchOrders()
    public var orderStatus = OrderStatus()
    public var deliveryType = DeliveryType()
    public var units = Units()
    public var settings = Settings()
    public var orderDetails = OrderDetails()
    public var login = Login()
    public var dashboard = Dashboard()
    public var defaultSection = DefaultSection()
    public var printer = Printer()

    enum CodingKeys: String, CodingKey {
        case orderDetailNewOrderSection
        case error
        case printerOutput
        case searchOrders
        case orderStatus
        case deliveryType
        case units
        case settings
        case orderDetails
        case login
        case dashboard
        case defaultSection = "default"
        case printer
    }

    public override init() { super.init() }

    public required init(from decoder: Decoder) throws {
        super.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        orderDetailNewOrderSection = try container.decodeIfPresent(OrderDetailNewOrderSection.self, forKey: .orderDetailNewOrderSection) ?? orderDetailNewOrderSection
        error = try container.decodeIfPresent(Error.self, forKey: .error) ?? error
        printerOutput = try container.decodeIfPresent(PrinterOutput.self, forKey: .printerOutput) ?? printerOutput
        searchOrders = try container.decodeIfPresent(SearchOrders.self, forKey: .searchOrders) ?? searchOrders
        orderStatus = try container.decodeIfPresent(OrderStatus.self, forKey: .orderStatus) ?? orderStatus
        deliveryType = try container.decodeIfPresent(DeliveryType.self, forKey: .deliveryType) ?? deliveryType
        units = try container.decodeIfPresent(Units.self, forKey: .units) ?? units
        settings = try container.decodeIfPresent(Settings.self, forKey: .settings) ?? settings
        orderDetails = try container.decodeIfPresent(OrderDetails.self, forKey: .orderDetails) ?? orderDetails
        login = try container.decodeIfPresent(Login.self, forKey: .login) ?? login
        dashboard = try container.decodeIfPresent(Dashboard.self, forKey: .dashboard) ?? dashboard
        defaultSection = try container.decodeIfPresent(DefaultSection.self, forKey: .defaultSection) ?? defaultSection
        printer = try container.decodeIfPresent(Printer.self, forKey: .printer) ?? printer
    }

    public override subscript(key: String) -> LocalizableSection? {
        switch key {
        case CodingKeys.orderDetailNewOrderSection.stringValue: return orderDetailNewOrderSection
        case CodingKeys.error.stringValue: return error
        case CodingKeys.printerOutput.stringValue: return printerOutput
        case CodingKeys.searchOrders.stringValue: return searchOrders
        case CodingKeys.orderStatus.stringValue: return orderStatus
        case CodingKeys.deliveryType.stringValue: return deliveryType
        case CodingKeys.units.stringValue: return units
        case CodingKeys.settings.stringValue: return settings
        case CodingKeys.orderDetails.stringValue: return orderDetails
        case CodingKeys.login.stringValue: return login
        case CodingKeys.dashboard.stringValue: return dashboard
        case CodingKeys.defaultSection.stringValue: return defaultSection
        case CodingKeys.printer.stringValue: return printer
        default: return nil
        }
    }

    public final class OrderDetailNewOrderSection: LocalizableSection {
        public var rejectButton = ""
        public var pickedUpInStoreAt = ""
        public var acceptButton = ""
        public var pickupTimeHeader = ""
        public var customerNameHeader = ""
        public var phoneNumberHeader = ""
        public var header = ""
        public var deliveryTimeHeader = ""
        public var subheader = ""

        enum CodingKeys: String, CodingKey {
            case rejectButton
            case pickedUpInStoreAt
            case acceptButton
            case pickupTimeHeader
            case customerNameHeader
            case phoneNumberHeader
            case header
            case deliveryTimeHeader
            case subheader
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            rejectButton = try container.decodeIfPresent(String.self, forKey: .rejectButton) ?? "__rejectButton"
            pickedUpInStoreAt = try container.decodeIfPresent(String.self, forKey: .pickedUpInStoreAt) ?? "__pickedUpInStoreAt"
            acceptButton = try container.decodeIfPresent(String.self, forKey: .acceptButton) ?? "__acceptButton"
            pickupTimeHeader = try container.decodeIfPresent(String.self, forKey: .pickupTimeHeader) ?? "__pickupTimeHeader"
            customerNameHeader = try container.decodeIfPresent(String.self, forKey: .customerNameHeader) ?? "__customerNameHeader"
            phoneNumberHeader = try container.decodeIfPresent(String.self, forKey: .phoneNumberHeader) ?? "__phoneNumberHeader"
            header = try container.decodeIfPresent(String.self, forKey: .header) ?? "__header"
            deliveryTimeHeader = try container.decodeIfPresent(String.self, forKey: .deliveryTimeHeader) ?? "__deliveryTimeHeader"
            subheader = try container.decodeIfPresent(String.self, forKey: .subheader) ?? "__subheader"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.rejectButton.stringValue: return rejectButton
            case CodingKeys.pickedUpInStoreAt.stringValue: return pickedUpInStoreAt
            case CodingKeys.acceptButton.stringValue: return acceptButton
            case CodingKeys.pickupTimeHeader.stringValue: return pickupTimeHeader
            case CodingKeys.customerNameHeader.stringValue: return customerNameHeader
            case CodingKeys.phoneNumberHeader.stringValue: return phoneNumberHeader
            case CodingKeys.header.stringValue: return header
            case CodingKeys.deliveryTimeHeader.stringValue: return deliveryTimeHeader
            case CodingKeys.subheader.stringValue: return subheader
            default: return nil
            }
        }
    }

    public final class Error: LocalizableSection {
        public var unknownError = ""
        public var authenticationError = ""
        public var serverError = ""
        public var errorTitle = ""
        public var connectionError = ""

        enum CodingKeys: String, CodingKey {
            case unknownError
            case authenticationError
            case serverError
            case errorTitle
            case connectionError
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            unknownError = try container.decodeIfPresent(String.self, forKey: .unknownError) ?? "__unknownError"
            authenticationError = try container.decodeIfPresent(String.self, forKey: .authenticationError) ?? "__authenticationError"
            serverError = try container.decodeIfPresent(String.self, forKey: .serverError) ?? "__serverError"
            errorTitle = try container.decodeIfPresent(String.self, forKey: .errorTitle) ?? "__errorTitle"
            connectionError = try container.decodeIfPresent(String.self, forKey: .connectionError) ?? "__connectionError"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.unknownError.stringValue: return unknownError
            case CodingKeys.authenticationError.stringValue: return authenticationError
            case CodingKeys.serverError.stringValue: return serverError
            case CodingKeys.errorTitle.stringValue: return errorTitle
            case CodingKeys.connectionError.stringValue: return connectionError
            default: return nil
            }
        }
    }

    public final class PrinterOutput: LocalizableSection {
        public var noteHeader = ""
        public var otherHeader = ""
        public var errorDeviceConnectionFailed = ""
        public var warmHeader = ""
        public var coldHeader = ""
        public var includeCutlery = ""
        public var orderNumber = ""
        public var errorNoDeviceFound = ""

        enum CodingKeys: String, CodingKey {
            case noteHeader
            case otherHeader
            case errorDeviceConnectionFailed
            case warmHeader
            case coldHeader
            case includeCutlery
            case orderNumber
            case errorNoDeviceFound
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            noteHeader = try container.decodeIfPresent(String.self, forKey: .noteHeader) ?? "__noteHeader"
            otherHeader = try container.decodeIfPresent(String.self, forKey: .otherHeader) ?? "__otherHeader"
            errorDeviceConnectionFailed = try container.decodeIfPresent(String.self, forKey: .errorDeviceConnectionFailed) ?? "__errorDeviceConnectionFailed"
            warmHeader = try container.decodeIfPresent(String.self, forKey: .warmHeader) ?? "__warmHeader"
            coldHeader = try container.decodeIfPresent(String.self, forKey: .coldHeader) ?? "__coldHeader"
            includeCutlery = try container.decodeIfPresent(String.self, forKey: .includeCutlery) ?? "__includeCutlery"
            orderNumber = try container.decodeIfPresent(String.self, forKey: .orderNumber) ?? "__orderNumber"
            errorNoDeviceFound = try container.decodeIfPresent(String.self, forKey: .errorNoDeviceFound) ?? "__errorNoDeviceFound"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.noteHeader.stringValue: return noteHeader
            case CodingKeys.otherHeader.stringValue: return otherHeader
            case CodingKeys.errorDeviceConnectionFailed.stringValue: return errorDeviceConnectionFailed
            case CodingKeys.warmHeader.stringValue: return warmHeader
            case CodingKeys.coldHeader.stringValue: return coldHeader
            case CodingKeys.includeCutlery.stringValue: return includeCutlery
            case CodingKeys.orderNumber.stringValue: return orderNumber
            case CodingKeys.errorNoDeviceFound.stringValue: return errorNoDeviceFound
            default: return nil
            }
        }
    }

    public final class SearchOrders: LocalizableSection {
        public var orderStatusHeader = ""
        public var searchfieldPlaceholder = ""
        public var orderNumberHeader = ""
        public var customerNameHeader = ""
        public var title = ""
        public var statusReady = ""
        public var statusCompleted = ""
        public var statusShipped = ""
        public var orderDateHeader = ""
        public var statusAccepted = ""
        public var emptyMessage = ""
        public var statusRejected = ""
        public var statusNew = ""

        enum CodingKeys: String, CodingKey {
            case orderStatusHeader
            case searchfieldPlaceholder
            case orderNumberHeader
            case customerNameHeader
            case title
            case statusReady
            case statusCompleted
            case statusShipped
            case orderDateHeader
            case statusAccepted
            case emptyMessage
            case statusRejected
            case statusNew
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            orderStatusHeader = try container.decodeIfPresent(String.self, forKey: .orderStatusHeader) ?? "__orderStatusHeader"
            searchfieldPlaceholder = try container.decodeIfPresent(String.self, forKey: .searchfieldPlaceholder) ?? "__searchfieldPlaceholder"
            orderNumberHeader = try container.decodeIfPresent(String.self, forKey: .orderNumberHeader) ?? "__orderNumberHeader"
            customerNameHeader = try container.decodeIfPresent(String.self, forKey: .customerNameHeader) ?? "__customerNameHeader"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            statusReady = try container.decodeIfPresent(String.self, forKey: .statusReady) ?? "__statusReady"
            statusCompleted = try container.decodeIfPresent(String.self, forKey: .statusCompleted) ?? "__statusCompleted"
            statusShipped = try container.decodeIfPresent(String.self, forKey: .statusShipped) ?? "__statusShipped"
            orderDateHeader = try container.decodeIfPresent(String.self, forKey: .orderDateHeader) ?? "__orderDateHeader"
            statusAccepted = try container.decodeIfPresent(String.self, forKey: .statusAccepted) ?? "__statusAccepted"
            emptyMessage = try container.decodeIfPresent(String.self, forKey: .emptyMessage) ?? "__emptyMessage"
            statusRejected = try container.decodeIfPresent(String.self, forKey: .statusRejected) ?? "__statusRejected"
            statusNew = try container.decodeIfPresent(String.self, forKey: .statusNew) ?? "__statusNew"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.orderStatusHeader.stringValue: return orderStatusHeader
            case CodingKeys.searchfieldPlaceholder.stringValue: return searchfieldPlaceholder
            case CodingKeys.orderNumberHeader.stringValue: return orderNumberHeader
            case CodingKeys.customerNameHeader.stringValue: return customerNameHeader
            case CodingKeys.title.stringValue: return title
            case CodingKeys.statusReady.stringValue: return statusReady
            case CodingKeys.statusCompleted.stringValue: return statusCompleted
            case CodingKeys.statusShipped.stringValue: return statusShipped
            case CodingKeys.orderDateHeader.stringValue: return orderDateHeader
            case CodingKeys.statusAccepted.stringValue: return statusAccepted
            case CodingKeys.emptyMessage.stringValue: return emptyMessage
            case CodingKeys.statusRejected.stringValue: return statusRejected
            case CodingKeys.statusNew.stringValue: return statusNew
            default: return nil
            }
        }
    }

    public final class OrderStatus: LocalizableSection {
        public var accepted = ""

        enum CodingKeys: String, CodingKey {
            case accepted
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            accepted = try container.decodeIfPresent(String.self, forKey: .accepted) ?? "__accepted"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.accepted.stringValue: return accepted
            default: return nil
            }
        }
    }

    public final class DeliveryType: LocalizableSection {
        public var delivery = ""
        public var collect = ""

        enum CodingKeys: String, CodingKey {
            case delivery
            case collect
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            delivery = try container.decodeIfPresent(String.self, forKey: .delivery) ?? "__delivery"
            collect = try container.decodeIfPresent(String.self, forKey: .collect) ?? "__collect"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.delivery.stringValue: return delivery
            case CodingKeys.collect.stringValue: return collect
            default: return nil
            }
        }
    }

    public final class Units: LocalizableSection {
        public var kgm = ""
        public var ltr = ""
        public var h87 = ""
        public var clt = ""
        public var d70 = ""
        public var grm = ""
        public var e14 = ""
        public var dlt = ""
        public var cmt = ""
        public var mlt = ""

        enum CodingKeys: String, CodingKey {
            case kgm
            case ltr
            case h87
            case clt
            case d70
            case grm
            case e14
            case dlt
            case cmt
            case mlt
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            kgm = try container.decodeIfPresent(String.self, forKey: .kgm) ?? "__kgm"
            ltr = try container.decodeIfPresent(String.self, forKey: .ltr) ?? "__ltr"
            h87 = try container.decodeIfPresent(String.self, forKey: .h87) ?? "__h87"
            clt = try container.decodeIfPresent(String.self, forKey: .clt) ?? "__clt"
            d70 = try container.decodeIfPresent(String.self, forKey: .d70) ?? "__d70"
            grm = try container.decodeIfPresent(String.self, forKey: .grm) ?? "__grm"
            e14 = try container.decodeIfPresent(String.self, forKey: .e14) ?? "__e14"
            dlt = try container.decodeIfPresent(String.self, forKey: .dlt) ?? "__dlt"
            cmt = try container.decodeIfPresent(String.self, forKey: .cmt) ?? "__cmt"
            mlt = try container.decodeIfPresent(String.self, forKey: .mlt) ?? "__mlt"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.kgm.stringValue: return kgm
            case CodingKeys.ltr.stringValue: return ltr
            case CodingKeys.h87.stringValue: return h87
            case CodingKeys.clt.stringValue: return clt
            case CodingKeys.d70.stringValue: return d70
            case CodingKeys.grm.stringValue: return grm
            case CodingKeys.e14.stringValue: return e14
            case CodingKeys.dlt.stringValue: return dlt
            case CodingKeys.cmt.stringValue: return cmt
            case CodingKeys.mlt.stringValue: return mlt
            default: return nil
            }
        }
    }

    public final class Settings: LocalizableSection {
        public var selectPrinterButton = ""
        public var logOutAlertMessage = ""
        public var printerHeader = ""
        public var appVersionHeader = ""
        public var usernameHeader = ""
        public var logoutAlertTitle = ""
        public var logOutAlertCancel = ""
        public var logOutAlertConfirm = ""
        public var logOutButton = ""
        public var closeButton = ""
        public var title = ""

        enum CodingKeys: String, CodingKey {
            case selectPrinterButton
            case logOutAlertMessage
            case printerHeader
            case appVersionHeader
            case usernameHeader
            case logoutAlertTitle
            case logOutAlertCancel
            case logOutAlertConfirm
            case logOutButton
            case closeButton
            case title
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            selectPrinterButton = try container.decodeIfPresent(String.self, forKey: .selectPrinterButton) ?? "__selectPrinterButton"
            logOutAlertMessage = try container.decodeIfPresent(String.self, forKey: .logOutAlertMessage) ?? "__logOutAlertMessage"
            printerHeader = try container.decodeIfPresent(String.self, forKey: .printerHeader) ?? "__printerHeader"
            appVersionHeader = try container.decodeIfPresent(String.self, forKey: .appVersionHeader) ?? "__appVersionHeader"
            usernameHeader = try container.decodeIfPresent(String.self, forKey: .usernameHeader) ?? "__usernameHeader"
            logoutAlertTitle = try container.decodeIfPresent(String.self, forKey: .logoutAlertTitle) ?? "__logoutAlertTitle"
            logOutAlertCancel = try container.decodeIfPresent(String.self, forKey: .logOutAlertCancel) ?? "__logOutAlertCancel"
            logOutAlertConfirm = try container.decodeIfPresent(String.self, forKey: .logOutAlertConfirm) ?? "__logOutAlertConfirm"
            logOutButton = try container.decodeIfPresent(String.self, forKey: .logOutButton) ?? "__logOutButton"
            closeButton = try container.decodeIfPresent(String.self, forKey: .closeButton) ?? "__closeButton"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.selectPrinterButton.stringValue: return selectPrinterButton
            case CodingKeys.logOutAlertMessage.stringValue: return logOutAlertMessage
            case CodingKeys.printerHeader.stringValue: return printerHeader
            case CodingKeys.appVersionHeader.stringValue: return appVersionHeader
            case CodingKeys.usernameHeader.stringValue: return usernameHeader
            case CodingKeys.logoutAlertTitle.stringValue: return logoutAlertTitle
            case CodingKeys.logOutAlertCancel.stringValue: return logOutAlertCancel
            case CodingKeys.logOutAlertConfirm.stringValue: return logOutAlertConfirm
            case CodingKeys.logOutButton.stringValue: return logOutButton
            case CodingKeys.closeButton.stringValue: return closeButton
            case CodingKeys.title.stringValue: return title
            default: return nil
            }
        }
    }

    public final class OrderDetails: LocalizableSection {
        public var pickedUpButton = ""
        public var infoAddress = ""
        public var sectionHeaderColdProducts = ""
        public var deliveryTypeHeader = ""
        public var infoTakeoutPhone = ""
        public var customerNoteHeader = ""
        public var errorStatusUpdateFailed = ""
        public var infoDeliveryTime = ""
        public var sectionHeaderCustomerInfo = ""
        public var sectionHeaderOtherProducts = ""
        public var underPreparationButton = ""
        public var errorCouldNotFetchProducts = ""
        public var infoPaymentType = ""
        public var rejectOrderAlertMessage = ""
        public var sectionSubheaderColdProducts = ""
        public var sectionHeaderOrderStatus = ""
        public var includeCutlery = ""
        public var readyButton = ""
        public var rejectButton = ""
        public var sectionHeaderWarmProducts = ""
        public var completedBanner = ""
        public var outForDeliveryButton = ""
        public var aPiece = ""
        public var rejectOrderAlertCancel = ""
        public var infoEmail = ""
        public var infoCustomerName = ""
        public var pickupTimeHeader = ""
        public var today = ""
        public var sectionHeaderTakeout = ""
        public var rejectOrderAlertConfirm = ""
        public var printButton = ""
        public var rejectOrderAlertTitle = ""
        public var infoOrderTime = ""
        public var infoTakeOutShopID = ""
        public var infoMobilePhone = ""

        enum CodingKeys: String, CodingKey {
            case pickedUpButton
            case infoAddress
            case sectionHeaderColdProducts
            case deliveryTypeHeader
            case infoTakeoutPhone
            case customerNoteHeader
            case errorStatusUpdateFailed
            case infoDeliveryTime
            case sectionHeaderCustomerInfo
            case sectionHeaderOtherProducts
            case underPreparationButton
            case errorCouldNotFetchProducts
            case infoPaymentType
            case rejectOrderAlertMessage
            case sectionSubheaderColdProducts
            case sectionHeaderOrderStatus
            case includeCutlery
            case readyButton
            case rejectButton
            case sectionHeaderWarmProducts
            case completedBanner
            case outForDeliveryButton
            case aPiece
            case rejectOrderAlertCancel
            case infoEmail
            case infoCustomerName
            case pickupTimeHeader
            case today
            case sectionHeaderTakeout
            case rejectOrderAlertConfirm
            case printButton
            case rejectOrderAlertTitle
            case infoOrderTime
            case infoTakeOutShopID
            case infoMobilePhone
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            pickedUpButton = try container.decodeIfPresent(String.self, forKey: .pickedUpButton) ?? "__pickedUpButton"
            infoAddress = try container.decodeIfPresent(String.self, forKey: .infoAddress) ?? "__infoAddress"
            sectionHeaderColdProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderColdProducts) ?? "__sectionHeaderColdProducts"
            deliveryTypeHeader = try container.decodeIfPresent(String.self, forKey: .deliveryTypeHeader) ?? "__deliveryTypeHeader"
            infoTakeoutPhone = try container.decodeIfPresent(String.self, forKey: .infoTakeoutPhone) ?? "__infoTakeoutPhone"
            customerNoteHeader = try container.decodeIfPresent(String.self, forKey: .customerNoteHeader) ?? "__customerNoteHeader"
            errorStatusUpdateFailed = try container.decodeIfPresent(String.self, forKey: .errorStatusUpdateFailed) ?? "__errorStatusUpdateFailed"
            infoDeliveryTime = try container.decodeIfPresent(String.self, forKey: .infoDeliveryTime) ?? "__infoDeliveryTime"
            sectionHeaderCustomerInfo = try container.decodeIfPresent(String.self, forKey: .sectionHeaderCustomerInfo) ?? "__sectionHeaderCustomerInfo"
            sectionHeaderOtherProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderOtherProducts) ?? "__sectionHeaderOtherProducts"
            underPreparationButton = try container.decodeIfPresent(String.self, forKey: .underPreparationButton) ?? "__underPreparationButton"
            errorCouldNotFetchProducts = try container.decodeIfPresent(String.self, forKey: .errorCouldNotFetchProducts) ?? "__errorCouldNotFetchProducts"
            infoPaymentType = try container.decodeIfPresent(String.self, forKey: .infoPaymentType) ?? "__infoPaymentType"
            rejectOrderAlertMessage = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertMessage) ?? "__rejectOrderAlertMessage"
            sectionSubheaderColdProducts = try container.decodeIfPresent(String.self, forKey: .sectionSubheaderColdProducts) ?? "__sectionSubheaderColdProducts"
            sectionHeaderOrderStatus = try container.decodeIfPresent(String.self, forKey: .sectionHeaderOrderStatus) ?? "__sectionHeaderOrderStatus"
            includeCutlery = try container.decodeIfPresent(String.self, forKey: .includeCutlery) ?? "__includeCutlery"
            readyButton = try container.decodeIfPresent(String.self, forKey: .readyButton) ?? "__readyButton"
            rejectButton = try container.decodeIfPresent(String.self, forKey: .rejectButton) ?? "__rejectButton"
            sectionHeaderWarmProducts = try container.decodeIfPresent(String.self, forKey: .sectionHeaderWarmProducts) ?? "__sectionHeaderWarmProducts"
            completedBanner = try container.decodeIfPresent(String.self, forKey: .completedBanner) ?? "__completedBanner"
            outForDeliveryButton = try container.decodeIfPresent(String.self, forKey: .outForDeliveryButton) ?? "__outForDeliveryButton"
            aPiece = try container.decodeIfPresent(String.self, forKey: .aPiece) ?? "__aPiece"
            rejectOrderAlertCancel = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertCancel) ?? "__rejectOrderAlertCancel"
            infoEmail = try container.decodeIfPresent(String.self, forKey: .infoEmail) ?? "__infoEmail"
            infoCustomerName = try container.decodeIfPresent(String.self, forKey: .infoCustomerName) ?? "__infoCustomerName"
            pickupTimeHeader = try container.decodeIfPresent(String.self, forKey: .pickupTimeHeader) ?? "__pickupTimeHeader"
            today = try container.decodeIfPresent(String.self, forKey: .today) ?? "__today"
            sectionHeaderTakeout = try container.decodeIfPresent(String.self, forKey: .sectionHeaderTakeout) ?? "__sectionHeaderTakeout"
            rejectOrderAlertConfirm = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertConfirm) ?? "__rejectOrderAlertConfirm"
            printButton = try container.decodeIfPresent(String.self, forKey: .printButton) ?? "__printButton"
            rejectOrderAlertTitle = try container.decodeIfPresent(String.self, forKey: .rejectOrderAlertTitle) ?? "__rejectOrderAlertTitle"
            infoOrderTime = try container.decodeIfPresent(String.self, forKey: .infoOrderTime) ?? "__infoOrderTime"
            infoTakeOutShopID = try container.decodeIfPresent(String.self, forKey: .infoTakeOutShopID) ?? "__infoTakeOutShopID"
            infoMobilePhone = try container.decodeIfPresent(String.self, forKey: .infoMobilePhone) ?? "__infoMobilePhone"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.pickedUpButton.stringValue: return pickedUpButton
            case CodingKeys.infoAddress.stringValue: return infoAddress
            case CodingKeys.sectionHeaderColdProducts.stringValue: return sectionHeaderColdProducts
            case CodingKeys.deliveryTypeHeader.stringValue: return deliveryTypeHeader
            case CodingKeys.infoTakeoutPhone.stringValue: return infoTakeoutPhone
            case CodingKeys.customerNoteHeader.stringValue: return customerNoteHeader
            case CodingKeys.errorStatusUpdateFailed.stringValue: return errorStatusUpdateFailed
            case CodingKeys.infoDeliveryTime.stringValue: return infoDeliveryTime
            case CodingKeys.sectionHeaderCustomerInfo.stringValue: return sectionHeaderCustomerInfo
            case CodingKeys.sectionHeaderOtherProducts.stringValue: return sectionHeaderOtherProducts
            case CodingKeys.underPreparationButton.stringValue: return underPreparationButton
            case CodingKeys.errorCouldNotFetchProducts.stringValue: return errorCouldNotFetchProducts
            case CodingKeys.infoPaymentType.stringValue: return infoPaymentType
            case CodingKeys.rejectOrderAlertMessage.stringValue: return rejectOrderAlertMessage
            case CodingKeys.sectionSubheaderColdProducts.stringValue: return sectionSubheaderColdProducts
            case CodingKeys.sectionHeaderOrderStatus.stringValue: return sectionHeaderOrderStatus
            case CodingKeys.includeCutlery.stringValue: return includeCutlery
            case CodingKeys.readyButton.stringValue: return readyButton
            case CodingKeys.rejectButton.stringValue: return rejectButton
            case CodingKeys.sectionHeaderWarmProducts.stringValue: return sectionHeaderWarmProducts
            case CodingKeys.completedBanner.stringValue: return completedBanner
            case CodingKeys.outForDeliveryButton.stringValue: return outForDeliveryButton
            case CodingKeys.aPiece.stringValue: return aPiece
            case CodingKeys.rejectOrderAlertCancel.stringValue: return rejectOrderAlertCancel
            case CodingKeys.infoEmail.stringValue: return infoEmail
            case CodingKeys.infoCustomerName.stringValue: return infoCustomerName
            case CodingKeys.pickupTimeHeader.stringValue: return pickupTimeHeader
            case CodingKeys.today.stringValue: return today
            case CodingKeys.sectionHeaderTakeout.stringValue: return sectionHeaderTakeout
            case CodingKeys.rejectOrderAlertConfirm.stringValue: return rejectOrderAlertConfirm
            case CodingKeys.printButton.stringValue: return printButton
            case CodingKeys.rejectOrderAlertTitle.stringValue: return rejectOrderAlertTitle
            case CodingKeys.infoOrderTime.stringValue: return infoOrderTime
            case CodingKeys.infoTakeOutShopID.stringValue: return infoTakeOutShopID
            case CodingKeys.infoMobilePhone.stringValue: return infoMobilePhone
            default: return nil
            }
        }
    }

    public final class Login: LocalizableSection {
        public var emailHeader = ""
        public var loginButton = ""
        public var passwordHeader = ""
        public var passwordPlaceholder = ""
        public var appName = ""
        public var appVersionPrefix = ""
        public var resetPasswordMessage = ""
        public var title = ""
        public var emailPlaceholder = ""
        public var errorInvalidCredentials = ""

        enum CodingKeys: String, CodingKey {
            case emailHeader
            case loginButton
            case passwordHeader
            case passwordPlaceholder
            case appName
            case appVersionPrefix
            case resetPasswordMessage
            case title
            case emailPlaceholder
            case errorInvalidCredentials
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            emailHeader = try container.decodeIfPresent(String.self, forKey: .emailHeader) ?? "__emailHeader"
            loginButton = try container.decodeIfPresent(String.self, forKey: .loginButton) ?? "__loginButton"
            passwordHeader = try container.decodeIfPresent(String.self, forKey: .passwordHeader) ?? "__passwordHeader"
            passwordPlaceholder = try container.decodeIfPresent(String.self, forKey: .passwordPlaceholder) ?? "__passwordPlaceholder"
            appName = try container.decodeIfPresent(String.self, forKey: .appName) ?? "__appName"
            appVersionPrefix = try container.decodeIfPresent(String.self, forKey: .appVersionPrefix) ?? "__appVersionPrefix"
            resetPasswordMessage = try container.decodeIfPresent(String.self, forKey: .resetPasswordMessage) ?? "__resetPasswordMessage"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            emailPlaceholder = try container.decodeIfPresent(String.self, forKey: .emailPlaceholder) ?? "__emailPlaceholder"
            errorInvalidCredentials = try container.decodeIfPresent(String.self, forKey: .errorInvalidCredentials) ?? "__errorInvalidCredentials"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.emailHeader.stringValue: return emailHeader
            case CodingKeys.loginButton.stringValue: return loginButton
            case CodingKeys.passwordHeader.stringValue: return passwordHeader
            case CodingKeys.passwordPlaceholder.stringValue: return passwordPlaceholder
            case CodingKeys.appName.stringValue: return appName
            case CodingKeys.appVersionPrefix.stringValue: return appVersionPrefix
            case CodingKeys.resetPasswordMessage.stringValue: return resetPasswordMessage
            case CodingKeys.title.stringValue: return title
            case CodingKeys.emailPlaceholder.stringValue: return emailPlaceholder
            case CodingKeys.errorInvalidCredentials.stringValue: return errorInvalidCredentials
            default: return nil
            }
        }
    }

    public final class Dashboard: LocalizableSection {
        public var sectionLater = ""
        public var columnOutForDelivery = ""
        public var columnIncomingEmpty = ""
        public var columnReady = ""
        public var columnReadyEmpty = ""
        public var columnAccepted = ""
        public var sectionToday = ""
        public var itemsPlural = ""
        public var columnOutForDeliveryEmpty = ""
        public var columnAcceptedEmpty = ""
        public var columnDoneToday = ""
        public var allOrdersButton = ""
        public var sectionTomorrow = ""
        public var columnDoneTodayEmpty = ""
        public var itemsSingular = ""
        public var columnIncoming = ""

        enum CodingKeys: String, CodingKey {
            case sectionLater
            case columnOutForDelivery
            case columnIncomingEmpty
            case columnReady
            case columnReadyEmpty
            case columnAccepted
            case sectionToday
            case itemsPlural
            case columnOutForDeliveryEmpty
            case columnAcceptedEmpty
            case columnDoneToday
            case allOrdersButton
            case sectionTomorrow
            case columnDoneTodayEmpty
            case itemsSingular
            case columnIncoming
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            sectionLater = try container.decodeIfPresent(String.self, forKey: .sectionLater) ?? "__sectionLater"
            columnOutForDelivery = try container.decodeIfPresent(String.self, forKey: .columnOutForDelivery) ?? "__columnOutForDelivery"
            columnIncomingEmpty = try container.decodeIfPresent(String.self, forKey: .columnIncomingEmpty) ?? "__columnIncomingEmpty"
            columnReady = try container.decodeIfPresent(String.self, forKey: .columnReady) ?? "__columnReady"
            columnReadyEmpty = try container.decodeIfPresent(String.self, forKey: .columnReadyEmpty) ?? "__columnReadyEmpty"
            columnAccepted = try container.decodeIfPresent(String.self, forKey: .columnAccepted) ?? "__columnAccepted"
            sectionToday = try container.decodeIfPresent(String.self, forKey: .sectionToday) ?? "__sectionToday"
            itemsPlural = try container.decodeIfPresent(String.self, forKey: .itemsPlural) ?? "__itemsPlural"
            columnOutForDeliveryEmpty = try container.decodeIfPresent(String.self, forKey: .columnOutForDeliveryEmpty) ?? "__columnOutForDeliveryEmpty"
            columnAcceptedEmpty = try container.decodeIfPresent(String.self, forKey: .columnAcceptedEmpty) ?? "__columnAcceptedEmpty"
            columnDoneToday = try container.decodeIfPresent(String.self, forKey: .columnDoneToday) ?? "__columnDoneToday"
            allOrdersButton = try container.decodeIfPresent(String.self, forKey: .allOrdersButton) ?? "__allOrdersButton"
            sectionTomorrow = try container.decodeIfPresent(String.self, forKey: .sectionTomorrow) ?? "__sectionTomorrow"
            columnDoneTodayEmpty = try container.decodeIfPresent(String.self, forKey: .columnDoneTodayEmpty) ?? "__columnDoneTodayEmpty"
            itemsSingular = try container.decodeIfPresent(String.self, forKey: .itemsSingular) ?? "__itemsSingular"
            columnIncoming = try container.decodeIfPresent(String.self, forKey: .columnIncoming) ?? "__columnIncoming"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.sectionLater.stringValue: return sectionLater
            case CodingKeys.columnOutForDelivery.stringValue: return columnOutForDelivery
            case CodingKeys.columnIncomingEmpty.stringValue: return columnIncomingEmpty
            case CodingKeys.columnReady.stringValue: return columnReady
            case CodingKeys.columnReadyEmpty.stringValue: return columnReadyEmpty
            case CodingKeys.columnAccepted.stringValue: return columnAccepted
            case CodingKeys.sectionToday.stringValue: return sectionToday
            case CodingKeys.itemsPlural.stringValue: return itemsPlural
            case CodingKeys.columnOutForDeliveryEmpty.stringValue: return columnOutForDeliveryEmpty
            case CodingKeys.columnAcceptedEmpty.stringValue: return columnAcceptedEmpty
            case CodingKeys.columnDoneToday.stringValue: return columnDoneToday
            case CodingKeys.allOrdersButton.stringValue: return allOrdersButton
            case CodingKeys.sectionTomorrow.stringValue: return sectionTomorrow
            case CodingKeys.columnDoneTodayEmpty.stringValue: return columnDoneTodayEmpty
            case CodingKeys.itemsSingular.stringValue: return itemsSingular
            case CodingKeys.columnIncoming.stringValue: return columnIncoming
            default: return nil
            }
        }
    }

    public final class DefaultSection: LocalizableSection {
        public var back = ""
        public var skip = ""
        public var edit = ""
        public var ok = ""
        public var later = ""
        public var save = ""
        public var previous = ""
        public var retry = ""
        public var yes = ""
        public var settings = ""
        public var no = ""
        public var next = ""
        public var cancel = ""

        enum CodingKeys: String, CodingKey {
            case back
            case skip
            case edit
            case ok
            case later
            case save
            case previous
            case retry
            case yes
            case settings
            case no
            case next
            case cancel
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            back = try container.decodeIfPresent(String.self, forKey: .back) ?? "__back"
            skip = try container.decodeIfPresent(String.self, forKey: .skip) ?? "__skip"
            edit = try container.decodeIfPresent(String.self, forKey: .edit) ?? "__edit"
            ok = try container.decodeIfPresent(String.self, forKey: .ok) ?? "__ok"
            later = try container.decodeIfPresent(String.self, forKey: .later) ?? "__later"
            save = try container.decodeIfPresent(String.self, forKey: .save) ?? "__save"
            previous = try container.decodeIfPresent(String.self, forKey: .previous) ?? "__previous"
            retry = try container.decodeIfPresent(String.self, forKey: .retry) ?? "__retry"
            yes = try container.decodeIfPresent(String.self, forKey: .yes) ?? "__yes"
            settings = try container.decodeIfPresent(String.self, forKey: .settings) ?? "__settings"
            no = try container.decodeIfPresent(String.self, forKey: .no) ?? "__no"
            next = try container.decodeIfPresent(String.self, forKey: .next) ?? "__next"
            cancel = try container.decodeIfPresent(String.self, forKey: .cancel) ?? "__cancel"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.back.stringValue: return back
            case CodingKeys.skip.stringValue: return skip
            case CodingKeys.edit.stringValue: return edit
            case CodingKeys.ok.stringValue: return ok
            case CodingKeys.later.stringValue: return later
            case CodingKeys.save.stringValue: return save
            case CodingKeys.previous.stringValue: return previous
            case CodingKeys.retry.stringValue: return retry
            case CodingKeys.yes.stringValue: return yes
            case CodingKeys.settings.stringValue: return settings
            case CodingKeys.no.stringValue: return no
            case CodingKeys.next.stringValue: return next
            case CodingKeys.cancel.stringValue: return cancel
            default: return nil
            }
        }
    }

    public final class Printer: LocalizableSection {
        public var bluetoothHintFooter = ""
        public var connectedSuccessMessage = ""
        public var sectionHeaderActivePrinter = ""
        public var errorSomethingHappened = ""
        public var deleteButton = ""
        public var sectionHeaderNewPrinters = ""
        public var title = ""
        public var connectButton = ""

        enum CodingKeys: String, CodingKey {
            case bluetoothHintFooter
            case connectedSuccessMessage
            case sectionHeaderActivePrinter
            case errorSomethingHappened
            case deleteButton
            case sectionHeaderNewPrinters
            case title
            case connectButton
        }

        public override init() { super.init() }

        public required init(from decoder: Decoder) throws {
            super.init()
            let container = try decoder.container(keyedBy: CodingKeys.self)
            bluetoothHintFooter = try container.decodeIfPresent(String.self, forKey: .bluetoothHintFooter) ?? "__bluetoothHintFooter"
            connectedSuccessMessage = try container.decodeIfPresent(String.self, forKey: .connectedSuccessMessage) ?? "__connectedSuccessMessage"
            sectionHeaderActivePrinter = try container.decodeIfPresent(String.self, forKey: .sectionHeaderActivePrinter) ?? "__sectionHeaderActivePrinter"
            errorSomethingHappened = try container.decodeIfPresent(String.self, forKey: .errorSomethingHappened) ?? "__errorSomethingHappened"
            deleteButton = try container.decodeIfPresent(String.self, forKey: .deleteButton) ?? "__deleteButton"
            sectionHeaderNewPrinters = try container.decodeIfPresent(String.self, forKey: .sectionHeaderNewPrinters) ?? "__sectionHeaderNewPrinters"
            title = try container.decodeIfPresent(String.self, forKey: .title) ?? "__title"
            connectButton = try container.decodeIfPresent(String.self, forKey: .connectButton) ?? "__connectButton"
        }

        public override subscript(key: String) -> String? {
            switch key {
            case CodingKeys.bluetoothHintFooter.stringValue: return bluetoothHintFooter
            case CodingKeys.connectedSuccessMessage.stringValue: return connectedSuccessMessage
            case CodingKeys.sectionHeaderActivePrinter.stringValue: return sectionHeaderActivePrinter
            case CodingKeys.errorSomethingHappened.stringValue: return errorSomethingHappened
            case CodingKeys.deleteButton.stringValue: return deleteButton
            case CodingKeys.sectionHeaderNewPrinters.stringValue: return sectionHeaderNewPrinters
            case CodingKeys.title.stringValue: return title
            case CodingKeys.connectButton.stringValue: return connectButton
            default: return nil
            }
        }
    }
}

